This file just checks the working of the saved models.

In [88]:
from sklearn.externals import joblib
d1 = joblib.load('forStandardScalingRF.pkl')
d2 = joblib.load('forStandardScalingTestRF.pkl')#loading the dataframes

In [93]:
#Standardize features by removing the mean and scaling to unit variance
import numpy as np
from sklearn.preprocessing import StandardScaler
e =StandardScaler()
d1 = e.fit_transform(d1)
d2 = e.transform(d2)

In [94]:
query=[[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,4.980e+00]]

In [95]:
e.transform(query)#after standard scaling

array([[-0.39516408,  0.34457842, -1.31906925, -0.27808871, -0.14681256,
         0.41318267, -0.13869178,  0.13825855, -0.98056911, -0.67224612,
        -1.54082594,  0.45391267, -1.1033787 ]])

In [96]:
t_query=e.transform(query)

In [97]:
t_query

array([[-0.39516408,  0.34457842, -1.31906925, -0.27808871, -0.14681256,
         0.41318267, -0.13869178,  0.13825855, -0.98056911, -0.67224612,
        -1.54082594,  0.45391267, -1.1033787 ]])

In [98]:
from sklearn.externals import joblib
m1 = joblib.load('rfholdout_model.pkl')#loading the model

In [99]:
m1.predict(t_query)#checking the accuracy

array([24.902])